CREATE TABLE PESSOAS(
    ID_PESSOAS INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATANASCIMENTO DATE
);
CREATE TABLE ENDERECOS(
    ID_ENDERECOS INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGRADOURO VARCHAR(100),
    CEP INTEGER,
    NUMERO INTEGER,
    CIDADE VARCHAR(100)
    ID_PESSOAS INTEGER,
    FOREIGN KEY (ID_PESSOAS) REFERENCES PESSOAS(ID_PESSOAS)
)